//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class abb_dom_materie_minist
    {
        public int AB9_ID { get; set; }
        public Nullable<int> AB9_MINIST_MA_ID { get; set; }
        public Nullable<int> AB9_DO_ID { get; set; }
        public Nullable<byte> AB9_FLAGSTATISTICHE { get; set; }
        public Nullable<System.DateTime> AB9_DATAAGG { get; set; }
        public string AB9_RELEASE { get; set; }
    }
}
