//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class abbinamento_esami_materie
    {
        public int AB5_ID { get; set; }
        public Nullable<int> AB5_ES_ID { get; set; }
        public Nullable<int> AB5_MA_ID { get; set; }
        public string AB5_RELEASE { get; set; }
        public Nullable<int> AB5_SOTTOES_ID { get; set; }
    }
}
