//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class dettaglioregole
    {
        public int DR_ID { get; set; }
        public Nullable<int> DR_RE_ID { get; set; }
        public string DR_DESCRIZIONE { get; set; }
        public string DR_MATERIE { get; set; }
        public Nullable<byte> DR_DA { get; set; }
        public Nullable<byte> DR_AD { get; set; }
        public int DR_PROG { get; set; }
        public Nullable<int> DR_MM_ID { get; set; }
        public string DR_ORDINE { get; set; }
        public string DR_AGGREGAZIONEESAMI { get; set; }
    }
}
