//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class domande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public domande()
        {
            this.risposte = new HashSet<risposte>();
        }
    
        public int DO_ID { get; set; }
        public Nullable<int> DO_MINIST_MA_ID { get; set; }
        public string DO_TESTO { get; set; }
        public string DO_IMG { get; set; }
        public Nullable<int> DO_AR_ID { get; set; }
        public string DO_CODICE_MINST { get; set; }
        public string DO_CODICE_EGAF { get; set; }
        public string DO_IMG2 { get; set; }
        public string DO_MULTIMEDIALE { get; set; }
        public Nullable<int> DO_STATISTICA { get; set; }
        public string DO_COMMENTO { get; set; }
        public Nullable<int> DO_FLAG_BLOCCATA { get; set; }
        public string DO_NOTE { get; set; }
        public Nullable<int> DO_FLAG_BLOCCATA_EGAF { get; set; }
        public string DO_NOTE_EGAF { get; set; }
        public string DO_TEORICOPRATICO { get; set; }
        public Nullable<int> DO_ES_ID { get; set; }
        public Nullable<int> DO_FLAG_OBSOLETA { get; set; }
        public string DO_TESTOCN { get; set; }
        public string DO_TESTOES { get; set; }
        public string DO_TESTOMA { get; set; }
        public string DO_TESTODE { get; set; }
        public string DO_TESTOGB { get; set; }
        public string DO_TESTOFR { get; set; }
        public string DO_TESTORU { get; set; }
        public Nullable<int> DO_PROGRESSIVO { get; set; }
        public Nullable<int> DO_STATISTICAV { get; set; }
        public Nullable<int> DO_STATISTICAF { get; set; }
        public string DO_GRDOMCORR { get; set; }
        public string DO_ALTROTESTO { get; set; }
        public string DO_TESTO_AIUTO { get; set; }
    
        public virtual tipocommissione tipocommissione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<risposte> risposte { get; set; }
        public virtual esami esami { get; set; }
    }
}
