//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class egafEntities : DbContext
    {
        public egafEntities()
            : base("name=egafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<abb_dom_materie_minist> abb_dom_materie_minist { get; set; }
        public DbSet<abbinamento_esami_materie> abbinamento_esami_materie { get; set; }
        public DbSet<dettaglioregole> dettaglioregole { get; set; }
        public DbSet<domande> domande { get; set; }
        public DbSet<esami> esami { get; set; }
        public DbSet<regole> regole { get; set; }
        public DbSet<releaseopere> releaseopere { get; set; }
        public DbSet<risposte> risposte { get; set; }
        public DbSet<tipocommissione> tipocommissione { get; set; }
        public DbSet<v_tipipatente> v_tipipatente { get; set; }
    }
}
