//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class egafEntities : DbContext
    {
        public egafEntities()
            : base("name=egafEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abb_dom_materie_minist> abb_dom_materie_minist { get; set; }
        public virtual DbSet<abbinamento_esami_materie> abbinamento_esami_materie { get; set; }
        public virtual DbSet<dettaglioregole> dettaglioregole { get; set; }
        public virtual DbSet<domande> domande { get; set; }
        public virtual DbSet<esami> esami { get; set; }
        public virtual DbSet<regole> regole { get; set; }
        public virtual DbSet<releaseopere> releaseopere { get; set; }
        public virtual DbSet<risposte> risposte { get; set; }
        public virtual DbSet<tipocommissione> tipocommissione { get; set; }
        public virtual DbSet<v_tipipatente> v_tipipatente { get; set; }
        public virtual DbSet<v_esami> v_esami { get; set; }
        public virtual DbSet<v_regole> v_regole { get; set; }
        public virtual DbSet<locks> locks { get; set; }
        public virtual DbSet<v_releaseopere> v_releaseopere { get; set; }
        public virtual DbSet<v_domerisp> v_domerisp { get; set; }
    }
}
