//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class regole
    {
        public int RE_ID { get; set; }
        public string RE_DESCRIZIONE { get; set; }
        public Nullable<int> RE_DOMXQUEST { get; set; }
        public Nullable<int> RE_RISXDOM { get; set; }
        public Nullable<int> RE_HDOM { get; set; }
        public Nullable<int> RE_HTESTODOM { get; set; }
        public Nullable<int> RE_HTESTORISP { get; set; }
        public Nullable<int> RE_HLINE { get; set; }
        public string RE_TIPOREGOLA { get; set; }
        public Nullable<byte> RE_DEFAULT { get; set; }
        public Nullable<int> RE_DOMXPAG { get; set; }
        public Nullable<int> RE_FONTSIZEDOM { get; set; }
        public Nullable<int> RE_FONTSIZERISP { get; set; }
        public Nullable<int> RE_WIMG { get; set; }
        public Nullable<int> RE_RIGHEWRAP { get; set; }
        public Nullable<int> RE_PERCENTUALE { get; set; }
        public string RE_TIPOCALCOLO { get; set; }
        public string RE_PARAMINTESTAZIONE { get; set; }
        public string RE_NUMERARISPOSTE { get; set; }
        public Nullable<int> RE_LIMITE_RISPFALSE { get; set; }
        public string RE_ORDINAMENTORISPOSTE { get; set; }
        public Nullable<int> RE_PUNTEGGIOMINIMO { get; set; }
        public Nullable<int> RE_PUNTEGGIOMASSIMO { get; set; }
        public Nullable<int> RE_ANZIANITA { get; set; }
        public Nullable<int> RE_PUNTMINIMOTOTALE { get; set; }
        public Nullable<int> RE_TEMPOESAME { get; set; }
        public string RE_ORDINAMENTODOMANDE { get; set; }
        public int RE_PROG { get; set; }
        public Nullable<int> RE_RISPMINIMECP { get; set; }
        public Nullable<int> RE_RISPMINIMECPANZ { get; set; }
        public Nullable<int> RE_LIMITE_MIN_RISPFALSE { get; set; }
        public Nullable<int> RE_VOTOMINIMOCP { get; set; }
        public string RE_TIPOCALCOLO_ESITO { get; set; }
        public Nullable<int> RE_TIPORIGADINAMICO { get; set; }
        public Nullable<int> RE_DOMXPAGNOIMG { get; set; }
        public Nullable<float> RE_PESORISPESATTE { get; set; }
        public Nullable<float> RE_PESORISPERRATE { get; set; }
        public Nullable<float> RE_PESORISPNONDATE { get; set; }
    }
}
