//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class releaseopere
    {
        public int RO_ID { get; set; }
        public Nullable<int> RO_TC_ID { get; set; }
        public Nullable<int> RO_RELEASE { get; set; }
        public Nullable<System.DateTime> RO_DATA { get; set; }
        public Nullable<int> RO_RELEASE_MULTIMEDIALE { get; set; }
        public string RO_DESCR_REL_MULTIMEDIALE { get; set; }
        public string RO_TIPOSEGMENTI { get; set; }
        public Nullable<int> RO_ESISTENZATESTO { get; set; }
        public Nullable<int> RO_ESISTENZAAUDIO { get; set; }
        public Nullable<int> RO_PUBBLICARELEASE { get; set; }
        public Nullable<int> RO_FONTQUESTFISSO { get; set; }
        public string RO_LINGUEAMMESSE { get; set; }
        public Nullable<int> RO_COMPATTALIVELLI { get; set; }
        public Nullable<int> RO_MULTIMEDIALEOLD { get; set; }
        public Nullable<int> RO_TESTORISPOSTA_CONTIENE_TESTODOMANDA { get; set; }
        public Nullable<int> RO_GENERAQUESTIONARI { get; set; }
        public string RO_ESCLUDI_CASIPRATICI { get; set; }
        public string RO_DATAVALIDITA_LICENZA { get; set; }
        public Nullable<int> RO_ALLIEVO_ESCLUDI_QUIZ_ARGOMENTO { get; set; }
        public Nullable<int> RO_ALLIEVO_ESCLUDI_QUIZ_DIFFICOLTA { get; set; }
    }
}
