//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class risposte
    {
        public int RI_ID { get; set; }
        public Nullable<int> RI_DO_ID { get; set; }
        public string RI_TESTOORDINE { get; set; }
        public string RI_TESTO { get; set; }
        public string RI_VF { get; set; }
        public string RI_COMMENTO { get; set; }
        public Nullable<int> RI_FLAG_BLOCCATA { get; set; }
        public string RI_NOTE { get; set; }
        public Nullable<int> RI_FLAG_BLOCCATA_EGAF { get; set; }
        public string RI_NOTE_EGAF { get; set; }
        public Nullable<int> RI_ES_ID { get; set; }
        public Nullable<int> RI_FLAG_OBSOLETA { get; set; }
        public Nullable<int> RI_ORDINAMENTOCASUALE { get; set; }
        public string RI_TESTOCN { get; set; }
        public string RI_TESTOES { get; set; }
        public string RI_TESTOMA { get; set; }
        public string RI_TESTODE { get; set; }
        public string RI_TESTOGB { get; set; }
        public string RI_TESTOFR { get; set; }
        public string RI_TESTORU { get; set; }
        public Nullable<int> RI_PROGRESSIVO { get; set; }
        public Nullable<int> RI_CODICE_MINIST { get; set; }
        public string RI_IMG { get; set; }
        public string RI_IMG2 { get; set; }
        public string RI_ALTROTESTO { get; set; }
    
        public virtual domande domande { get; set; }
        [NotMapped]
        public virtual tipocommissione tipocommissione { get; set; }
    }
}
