//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocommissione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipocommissione()
        {
            this.domande = new HashSet<domande>();
            this.esami = new HashSet<esami>();
            this.risposte = new HashSet<risposte>();
        }
    
        public int TC_ID { get; set; }
        public string TC_DESCRIZIONE { get; set; }
        public string TC_TESTOVERBALE { get; set; }
        public string TC_TESTOATTESTATO { get; set; }
        public Nullable<byte> TC_ESAMEAPERTO { get; set; }
        public Nullable<int> TC_PROT_VERBALE { get; set; }
        public Nullable<int> TC_TIPO_PROT_VERB { get; set; }
        public Nullable<int> TC_PROT_ATTESTATO { get; set; }
        public Nullable<int> TC_TIPO_PROT_ATT { get; set; }
        public Nullable<int> TC_SIMULAZIONE_ESAME { get; set; }
        public Nullable<int> TC_CASOPRATICO { get; set; }
        public Nullable<int> TC_RELEASE { get; set; }
        public Nullable<int> TC_QUESTIONARIOMINIST { get; set; }
        public Nullable<byte> TC_ESAMEINLINGUA { get; set; }
        public Nullable<byte> TC_QUIZACASA { get; set; }
        public Nullable<byte> TC_MULTIESAME { get; set; }
        public Nullable<int> TC_CASOPRATICODETT { get; set; }
        public Nullable<int> TC_FONTQUESTFISSO { get; set; }
        public Nullable<int> TC_RIEPILOGOMACROMAT { get; set; }
        public Nullable<byte> TC_PERSONALIZZAREGOLE { get; set; }
        public Nullable<byte> TC_PERSONALIZZAREGOLECP { get; set; }
        public Nullable<int> TC_PARAMETRIFLASH { get; set; }
        public Nullable<int> TC_MODODOMMULTIMED { get; set; }
        public Nullable<int> TC_GESTIONESEMPLIFICATA { get; set; }
        public Nullable<int> TC_QUEST_CON_IMG { get; set; }
        public Nullable<int> TC_DEFAULT_CHK_IMG { get; set; }
        public Nullable<int> TC_CONSENTIDOMCORR { get; set; }
        public string TC_PLAYCONTINUO { get; set; }
        public Nullable<int> TC_LIVELLOLEZIONE { get; set; }
        public Nullable<int> TC_TEMPODOMANDA { get; set; }
        public Nullable<int> TC_TEMPORISPOSTA { get; set; }
        public Nullable<int> TC_TEMPOIMMAGINE { get; set; }
        public string TC_MOSTRACOLOREARG { get; set; }
        public string TC_TOOLTIPTABELLONE { get; set; }
        public string TC_AUTOPLAY { get; set; }
        public string TC_RISPOSTEBARRA { get; set; }
        public string TC_FLASHCHIUDIFILM { get; set; }
        public string TC_FLASHATTIVAQUIZ { get; set; }
        public string TC_FLASHATTIVASUGGER { get; set; }
        public string TC_FLASHATTIVAZOOMINIZIALE { get; set; }
        public string TC_FLASHATTIVAAUDIO { get; set; }
        public string TC_ORDINAMENTOCASUALE { get; set; }
        public Nullable<int> TC_MOSTRALEGENDAARG { get; set; }
        public string TC_MINIMIZED { get; set; }
        public string TC_ATTIVA_SUGG_VF { get; set; }
        public string TC_ATTIVA_ANTE_DOMANDA { get; set; }
        public string TC_MOSTRAPROGDOM { get; set; }
        public Nullable<int> TC_MAXLIVARGOMENTI { get; set; }
        public string TC_NASCONDI_PROG_CAP { get; set; }
        public string TC_GESTIONEDISPENSATO { get; set; }
        public string TC_ATTIVA_TEMPORISPOSTA { get; set; }
        public string TC_ATTIVA_AVANZAM_MANUALE { get; set; }
        public string TC_ATTIVA_VF_CON_AUDIO { get; set; }
        public string TC_NASCONDI_MINIATURE { get; set; }
        public string TC_GEN_QUEST_LEZ_LIBERA { get; set; }
        public string TC_AGGIORNA_PRESENZA { get; set; }
        public string TC_AUDIOPRIMADOMANDA { get; set; }
        public string TC_ATTIVAQUIZ { get; set; }
        public string TC_USADOMANDEPERSONALIZZATE { get; set; }
        public string TC_MM_MULTIDB { get; set; }
        public string TC_MENUMULTIESAME { get; set; }
        public string TC_MM_REVISIONE { get; set; }
        public string TC_TACHIGRAFO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<domande> domande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<esami> esami { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<risposte> risposte { get; set; }
    }
}
