//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using DevExpress.Xpo;
    using System;
    using System.Collections.Generic;

    public partial class v_domerisp
    {
        public int DO_ID { get; set; }
        [Key]
        public int RI_ID { get; set; }
        public Nullable<int> DO_ES_ID { get; set; }
        public Nullable<int> RI_ES_ID { get; set; }
        public string DO_CODICE_MINST { get; set; }
        public string DO_CODICE_EGAF { get; set; }
        public string DO_TESTO { get; set; }
        public string RI_TESTOORDINE { get; set; }
        public string DO_TESTODE { get; set; }
        public string DO_TESTOFR { get; set; }
        public string RI_TESTO { get; set; }
        public string RI_TESTODE { get; set; }
        public string RI_TESTOFR { get; set; }
        public string RI_VF { get; set; }
        public string DO_IMG { get; set; }
        public string DO_IMG2 { get; set; }
        public Nullable<int> DO_FLAG_BLOCCATA { get; set; }
        public string DO_NOTE { get; set; }
        public Nullable<int> RI_FLAG_BLOCCATA { get; set; }
        public string RI_NOTE { get; set; }
        public string DO_ALTROTESTO { get; set; }
        public string DO_TESTO_AIUTO { get; set; }
        public string DO_GRDOMCORR { get; set; }
        public string RI_IMG { get; set; }
        public string RI_IMG2 { get; set; }
        public string RI_ALTROTESTO { get; set; }
        public Nullable<int> RI_ORDINAMENTOCASUALE { get; set; }
        public string DO_MULTIMEDIALE { get; set; }
    }
}
