//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_esami
    {
        public Nullable<int> ES_TC_ID { get; set; }
        public int ES_ID { get; set; }
        public string ES_DESCRIZIONE { get; set; }
        public Nullable<int> ES_RE_ID { get; set; }
        public Nullable<byte> ES_REVISIONE { get; set; }
        public Nullable<byte> ES_NONSELEZIONABILE { get; set; }
    }
}
