//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneDomandeDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_releaseopere
    {
        public int RO_ID { get; set; }
        public Nullable<int> RO_TC_ID { get; set; }
        public Nullable<int> RO_TESTORISPOSTA_CONTIENE_TESTODOMANDA { get; set; }
    }
}
